version: '2.2'

services:
  sh:
    extends:
      service: sh72

  sh-xdebug:
    extends:
      service: sh72-xdebug

  sh72:
    image: kiboko/php:7.2-cli-blackfire
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"
    command: [ "sleep", "31536000" ]

  sh72-xdebug:
    image: kiboko/php:7.2-cli-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"
    command: [ "sleep", "31536000" ]

  sh74:
    image: kiboko/php:7.4-cli-blackfire
    user: docker:docker
    volumes:
      - ./.docker/php@7.4/cli/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"
    command: [ "sleep", "31536000" ]

  sh74-xdebug:
    image: kiboko/php:7.4-cli-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.4/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"
    command: [ "sleep", "31536000" ]
